version: '3'

services:
  registry.local:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: http://idwerk.local:4000/api/oauth2/v1/auth
      REGISTRY_AUTH_TOKEN_SERVICE: registry.local
      REGISTRY_AUTH_TOKEN_ISSUER: idwerk.local
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/rootcertbundle.pem
    volumes:
      - ${PWD}/priv/tmp/certs:/certs
    depends_on:
      - idwerk.local
  db.local:
    image: postgres
  idwerk.local:
    build: .
    environment:
      DB_HOSTNAME: db.local
    command: mix phx.server
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    depends_on:
      - db.local



